alias c='clear'
alias cd..='cd ..'
alias ..='cd ..'
alias diff='colordiff'
alias mount='mount | column -t'
alias h='history'
alias j='jobs -l'
alias path='echo -e ${PATH//:/\\n}'
alias now='date +%T'
alias nowdate='date +"%d-%m-%Y"'
alias vi=vim
alias svim='sudo vim'
alias edit='vim'
alias ports='netstat -tulanp'
alias apt-get="sudo apt-get"
alias update="sudo apt-get update"
alias su="sudo -i"
alias reboot='sudo /sbin/reboot'
alias shutdown='sudo /sbin/shutdown -h now'
alias top='atop'
